package ROFA;


import java.awt.Color;
import java.text.DecimalFormat;
import java.util.Map;
//import java.util.LinkedList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class MainFrame extends javax.swing.JFrame {
    
    final IFurnitureManager _furnitureManager;
    
    /**
     * Creates new form MainFrame
     */
    
    
    public MainFrame() {
        initComponents();
        this._furnitureManager = new FurnitureManager();
    }

    
    //other methods
    private void addGridImage(String image, int pos, int idNumber){
        
        ImageIcon icon = new ImageIcon(getClass().getResource(image));
        icon.getImage().flush();
//        int imgHeight = icon.getIconHeight();
//        int imgWidth = icon.getIconWidth(); //grid1.setPreferredSize(new Dimension(imgWidth, imgHeight));
        
        
        switch(pos){
            case 1 -> {
                grid1.setIcon(icon);
                if(idNumber != 0) grid1.setText(Integer.toString(idNumber));
            }
            case 2 -> {
                grid2.setIcon(icon);
                if(idNumber != 0) grid2.setText(Integer.toString(idNumber));
            }
            case 3 -> {
                grid3.setIcon(icon);
                if(idNumber != 0) grid3.setText(Integer.toString(idNumber));
            }
            case 4 -> {
                grid4.setIcon(icon);
                if(idNumber != 0) grid4.setText(Integer.toString(idNumber));
            }
            case 5 -> {
                grid5.setIcon(icon);
                if(idNumber != 0) grid5.setText(Integer.toString(idNumber));
            }
            case 6 -> {
                grid6.setIcon(icon);
                if(idNumber != 0) grid6.setText(Integer.toString(idNumber));
            }
            case 7 -> {
                grid7.setIcon(icon);
                if(idNumber != 0) grid7.setText(Integer.toString(idNumber));
            }
            case 8 -> {
                grid8.setIcon(icon);
                if(idNumber != 0) grid8.setText(Integer.toString(idNumber));
            }
            case 9 -> {
                grid9.setIcon(icon);
                if(idNumber != 0) grid9.setText(Integer.toString(idNumber));
            }
            default -> {
            }
        }
    }
    
    private void updateTotalPriceGUI(){
        DecimalFormat formatter = new DecimalFormat("###,###,##0.00");
        mainTotalotalPrice.setText(formatter.format( _furnitureManager.getTotalOrderPrice()));
    }
    
    private void gridClick(java.awt.event.MouseEvent evt, JLabel grid){
        int idNumber = "".equals(grid.getText()) ? 0 : Integer.parseInt(grid.getText());
        if(evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            if(idNumber > 0) displayItemDetails(idNumber);
        }
        if(evt.getButton() == java.awt.event.MouseEvent.BUTTON2) {
            //
        }
        if(evt.getButton() == java.awt.event.MouseEvent.BUTTON3) {
            if(idNumber > 0) removeGridItem(grid);
        }
    }
    
    private void checkEmptyGrid(JLabel grid){
        if("".equals(grid.getText())){
            JOptionPane.showMessageDialog(jPanel4, "Oops, No item added to this grid yet.");
        }
    }
    
    private void displayItemDetails(int idNumber){
        _furnitureManager.displayItemOnConsole(idNumber);
        JOptionPane.showMessageDialog(jPanel4, "Details displayed to console.");
    }
    
    public void removeGridItem(JLabel grid){
        int idNumber = "".equals(grid.getText()) ? 0 : Integer.parseInt(grid.getText());
        
        if(_furnitureManager.checkIdNumberExists(idNumber)){
            int optionPane = JOptionPane.showConfirmDialog(jPanel4, "Please confirm action ?");
            if(optionPane == JOptionPane.YES_OPTION){
                this.addGridImage("", _furnitureManager.getOrderGridPosition(idNumber), 0);
                grid.setText("");
                _furnitureManager.removeGridItem(idNumber);
                this.updateTotalPriceGUI();
            }
        }
    }
    
    //private void clearAllOrder
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseGroup = new javax.swing.ButtonGroup();
        chairDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        chairIdNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        chairWoodType = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        chairQty = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        chairArmRests = new javax.swing.JCheckBox();
        addChairBtn = new javax.swing.JButton();
        closeChairForm = new javax.swing.JButton();
        tableDialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        tableIdNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tableWoodtype = new javax.swing.JComboBox<>();
        tableQty = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addTableBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tableDiameter = new javax.swing.JTextField();
        woodenBase = new javax.swing.JRadioButton();
        chromeBase = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        closeTableForm = new javax.swing.JButton();
        deskDialog = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        deskDrawers = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        deskWidth = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        deskQty = new javax.swing.JTextField();
        deskWoodType = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        deskIdNumber = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        addDeskBtn = new javax.swing.JButton();
        closeDeskBtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        deskDepth = new javax.swing.JTextField();
        displayItemDialog = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        dialogImg = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        displayIdNumber = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        displayItem = new javax.swing.JLabel();
        displayWoodType = new javax.swing.JLabel();
        displayPrice = new javax.swing.JLabel();
        displayQty = new javax.swing.JLabel();
        displayTotalPrice = new javax.swing.JLabel();
        paymentDetailsDialog = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        paymentPAN = new javax.swing.JTextField();
        paymentExpDate = new javax.swing.JTextField();
        paymentCardHolder = new javax.swing.JTextField();
        paymentCVV = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        mainTotalotalPrice = new javax.swing.JLabel();
        mainAddChairBtn = new javax.swing.JButton();
        mainAddTable = new javax.swing.JButton();
        mainAddDesk = new javax.swing.JButton();
        mainClearAll = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        placeOrderBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        grid1 = new javax.swing.JLabel();
        grid2 = new javax.swing.JLabel();
        grid3 = new javax.swing.JLabel();
        grid6 = new javax.swing.JLabel();
        grid4 = new javax.swing.JLabel();
        grid5 = new javax.swing.JLabel();
        grid7 = new javax.swing.JLabel();
        grid8 = new javax.swing.JLabel();
        grid9 = new javax.swing.JLabel();

        chairDialog.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Chair");

        jLabel10.setText("ID Number:");

        chairIdNumber.setText("1");
        chairIdNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                chairIdNumberFocusLost(evt);
            }
        });

        jLabel7.setText("Type of Wood:");

        chairWoodType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oak", "Walnut" }));

        jLabel11.setText("Quantity");

        chairQty.setText("1");
        chairQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                qtyValidation(evt);
            }
        });

        jLabel12.setText("Armrests");

        addChairBtn.setText("Add");
        addChairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChairBtnActionPerformed(evt);
            }
        });

        closeChairForm.setText("Close");
        closeChairForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeChairFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(chairIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(chairWoodType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chairArmRests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chairQty)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addChairBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeChairForm)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(chairIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chairWoodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chairQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(chairArmRests))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeChairForm)
                    .addComponent(addChairBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout chairDialogLayout = new javax.swing.GroupLayout(chairDialog.getContentPane());
        chairDialog.getContentPane().setLayout(chairDialogLayout);
        chairDialogLayout.setHorizontalGroup(
            chairDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        chairDialogLayout.setVerticalGroup(
            chairDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tableDialog.setResizable(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        tableIdNumber.setText("1");
        tableIdNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tableIdNumberFocusLost(evt);
            }
        });

        jLabel8.setText("Type of Wood:");

        tableWoodtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oak", "Walnut" }));

        tableQty.setText("1");
        tableQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tableQtyFocusLost(evt);
            }
        });

        jLabel9.setText("Quantity");

        jLabel13.setText("ID Number:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Table");

        addTableBtn.setText("Add");
        addTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTableBtnActionPerformed(evt);
            }
        });

        jLabel14.setText("Size (must be 50cm Upward):");

        tableDiameter.setText("50");
        tableDiameter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tableDiameterFocusLost(evt);
            }
        });

        baseGroup.add(woodenBase);
        woodenBase.setSelected(true);
        woodenBase.setText("Wooden Base");

        baseGroup.add(chromeBase);
        chromeBase.setText("Chrome Base");

        jLabel4.setText("Base:");

        closeTableForm.setText("Close");
        closeTableForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeTableFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tableQty)
                                    .addComponent(tableWoodtype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tableIdNumber)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(addTableBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(closeTableForm))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tableDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(woodenBase, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chromeBase, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tableIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tableWoodtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(tableQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tableDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(woodenBase)))
                    .addComponent(chromeBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTableBtn)
                    .addComponent(closeTableForm))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tableDialogLayout = new javax.swing.GroupLayout(tableDialog.getContentPane());
        tableDialog.getContentPane().setLayout(tableDialogLayout);
        tableDialogLayout.setHorizontalGroup(
            tableDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tableDialogLayout.setVerticalGroup(
            tableDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableDialogLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        deskDialog.setResizable(false);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        deskDrawers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jLabel15.setText("Drawers:");

        deskWidth.setText("50");
        deskWidth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                deskWidthFocusLost(evt);
            }
        });

        jLabel16.setText("Width (cm):");

        jLabel17.setText("Quantity");

        deskQty.setText("1");
        deskQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                deskQtyFocusLost(evt);
            }
        });

        deskWoodType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oak", "Walnut" }));

        jLabel18.setText("Type of Wood:");

        jLabel19.setText("ID Number:");

        deskIdNumber.setText("1");
        deskIdNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                deskIdNumberFocusLost(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Add Desk");

        addDeskBtn.setText("Add");
        addDeskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeskBtnActionPerformed(evt);
            }
        });

        closeDeskBtn.setText("Close");
        closeDeskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeDeskBtnActionPerformed(evt);
            }
        });

        jLabel21.setText("Depth (cm):");

        deskDepth.setText("50");
        deskDepth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                deskDepthFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(addDeskBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeDeskBtn))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(deskDrawers, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(deskWoodType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deskIdNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(deskQty)
                                .addComponent(deskWidth)
                                .addComponent(deskDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(deskIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(deskWoodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(deskQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deskWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deskDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(deskDrawers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDeskBtn)
                    .addComponent(closeDeskBtn))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout deskDialogLayout = new javax.swing.GroupLayout(deskDialog.getContentPane());
        deskDialog.getContentPane().setLayout(deskDialogLayout);
        deskDialogLayout.setHorizontalGroup(
            deskDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        deskDialogLayout.setVerticalGroup(
            deskDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialogImg.setForeground(new java.awt.Color(242, 242, 242));
        dialogImg.setOpaque(true);
        dialogImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dialogImgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dialogImg, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dialogImg, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("ID Number: ");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Wood Type: ");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Price (per each): ");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Total Price");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Quantity:");

        displayIdNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        displayIdNumber.setText(" ");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Item:");

        displayItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        displayItem.setText(" ");

        displayWoodType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        displayWoodType.setText(" ");

        displayPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        displayPrice.setText(" ");

        displayQty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        displayQty.setText(" ");

        displayTotalPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        displayTotalPrice.setText(" ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(displayWoodType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(displayIdNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(displayItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(displayWoodType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(displayPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(displayQty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(displayTotalPrice))
                .addContainerGap())
        );

        javax.swing.GroupLayout displayItemDialogLayout = new javax.swing.GroupLayout(displayItemDialog.getContentPane());
        displayItemDialog.getContentPane().setLayout(displayItemDialogLayout);
        displayItemDialogLayout.setHorizontalGroup(
            displayItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayItemDialogLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        displayItemDialogLayout.setVerticalGroup(
            displayItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayItemDialogLayout.createSequentialGroup()
                .addGroup(displayItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        paymentDetailsDialog.setMinimumSize(new java.awt.Dimension(383, 153));
        paymentDetailsDialog.setPreferredSize(new java.awt.Dimension(400, 180));
        paymentDetailsDialog.setResizable(false);
        paymentDetailsDialog.setSize(new java.awt.Dimension(390, 200));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Card PAN: ");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Expiry Date: ");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setText("Card Holder Name:");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setText("CVV:");

        jButton1.setText("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        paymentPAN.setText("123456789");

        paymentExpDate.setText("01/27");

        paymentCardHolder.setText("TEST HOLDER");

        paymentCVV.setText("123");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paymentPAN)
                    .addComponent(paymentExpDate)
                    .addComponent(paymentCardHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(paymentCVV, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(paymentPAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentCardHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paymentDetailsDialogLayout = new javax.swing.GroupLayout(paymentDetailsDialog.getContentPane());
        paymentDetailsDialog.getContentPane().setLayout(paymentDetailsDialogLayout);
        paymentDetailsDialogLayout.setHorizontalGroup(
            paymentDetailsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        paymentDetailsDialogLayout.setVerticalGroup(
            paymentDetailsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentDetailsDialogLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ROFApplication");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.lightGray)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Total Price = ");

        mainTotalotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mainTotalotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mainTotalotalPrice.setText("0.00");

        mainAddChairBtn.setText("Add Chair");
        mainAddChairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainAddChairBtnActionPerformed(evt);
            }
        });

        mainAddTable.setText("Add Table");
        mainAddTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainAddTableActionPerformed(evt);
            }
        });

        mainAddDesk.setText("Add Desk");
        mainAddDesk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainAddDeskActionPerformed(evt);
            }
        });

        mainClearAll.setText("Clear All");
        mainClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainClearAllActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("£");

        placeOrderBtn.setText("Place Order");
        placeOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mainAddChairBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainAddTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainAddDesk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainClearAll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainTotalotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(placeOrderBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainAddChairBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainAddTable, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainAddDesk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(placeOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainTotalotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(202, 202));

        grid1.setForeground(new java.awt.Color(242, 242, 242));
        grid1.setOpaque(true);
        grid1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid1MouseClicked(evt);
            }
        });

        grid2.setForeground(new java.awt.Color(242, 242, 242));
        grid2.setOpaque(true);
        grid2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid2MouseClicked(evt);
            }
        });

        grid3.setForeground(new java.awt.Color(242, 242, 242));
        grid3.setOpaque(true);
        grid3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid3MouseClicked(evt);
            }
        });

        grid6.setForeground(new java.awt.Color(242, 242, 242));
        grid6.setOpaque(true);
        grid6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid6MouseClicked(evt);
            }
        });

        grid4.setForeground(new java.awt.Color(242, 242, 242));
        grid4.setOpaque(true);
        grid4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid4MouseClicked(evt);
            }
        });

        grid5.setForeground(new java.awt.Color(242, 242, 242));
        grid5.setOpaque(true);
        grid5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid5MouseClicked(evt);
            }
        });

        grid7.setForeground(new java.awt.Color(242, 242, 242));
        grid7.setOpaque(true);
        grid7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid7MouseClicked(evt);
            }
        });

        grid8.setForeground(new java.awt.Color(242, 242, 242));
        grid8.setOpaque(true);
        grid8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid8MouseClicked(evt);
            }
        });

        grid9.setForeground(new java.awt.Color(242, 242, 242));
        grid9.setOpaque(true);
        grid9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(grid1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(grid4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(grid7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid8, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid9, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grid2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grid3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grid1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grid5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grid6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grid4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grid8, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grid9, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grid7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainAddChairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainAddChairBtnActionPerformed
        chairDialog.setVisible(true);
        chairDialog.setSize(330,225);
        chairDialog.setLocationRelativeTo(jPanel4);
    }//GEN-LAST:event_mainAddChairBtnActionPerformed

    private void mainAddTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainAddTableActionPerformed
        tableDialog.setVisible(true);
        tableDialog.setSize(415,265);
        tableDialog.setLocationRelativeTo(jPanel4);
    }//GEN-LAST:event_mainAddTableActionPerformed

    private void addChairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChairBtnActionPerformed
        if(_furnitureManager.checkOrderCapacity()){
            
            int idNumber = Integer.parseInt(chairIdNumber.getText());
            
            if(_furnitureManager.checkIdNumberExists(idNumber)){
                JOptionPane.showMessageDialog(jPanel4, "Oops, ID in use.");
                return;
            }
                
            String woodType = chairWoodType.getSelectedItem().toString();
            int qty = Integer.parseInt(chairQty.getText());
            boolean armRests = chairArmRests.isSelected();
            
            Chair newChair = _furnitureManager.addNewChair(idNumber, woodType, qty, armRests);
            this.addGridImage(newChair.image, _furnitureManager.getOrderGridPosition(newChair.idNumber), newChair.idNumber);
            this.updateTotalPriceGUI();
            closeChairFormActionPerformed(evt);
            
        }
        else{
            JOptionPane.showMessageDialog(jPanel4, "Oops, you've reached the maximum number of items that can be added into cart.");
        }
    }//GEN-LAST:event_addChairBtnActionPerformed

    private void closeChairFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeChairFormActionPerformed
       chairDialog.dispose();
       chairIdNumber.setText("1");
       //chairWoodType.setSelectedIndex(0);
       chairQty.setText("1");
       chairArmRests.setSelected(false);
    }//GEN-LAST:event_closeChairFormActionPerformed

    private void qtyValidation(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtyValidation
        try {
            int x = Integer.parseInt(chairQty.getText());
        } catch (NumberFormatException nfe) {
            chairQty.setText("1");
        }
    }//GEN-LAST:event_qtyValidation

    private void chairIdNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chairIdNumberFocusLost
        try {
            int x = Integer.parseInt(chairIdNumber.getText());
        } catch (NumberFormatException nfe) {
            chairIdNumber.setText("1");
        }
    }//GEN-LAST:event_chairIdNumberFocusLost

    private void closeTableFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeTableFormActionPerformed
       tableDialog.dispose();
       tableIdNumber.setText("1");
       tableQty.setText("1");
       tableDiameter.setText("50");
       
    }//GEN-LAST:event_closeTableFormActionPerformed

    private void tableIdNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableIdNumberFocusLost
        try {
            int x = Integer.parseInt(tableIdNumber.getText());
        } catch (NumberFormatException nfe) {
            tableIdNumber.setText("1");
        }
    }//GEN-LAST:event_tableIdNumberFocusLost

    private void tableQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableQtyFocusLost
        try {
            int x = Integer.parseInt(tableQty.getText());
        } catch (NumberFormatException nfe) {
            tableQty.setText("1");
        }
    }//GEN-LAST:event_tableQtyFocusLost

    private void tableDiameterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableDiameterFocusLost
        try {
            int x = Integer.parseInt(tableDiameter.getText());
            if(x < 50){
                JOptionPane.showMessageDialog(jPanel4, "Diameter must be 50cm or above.");
                tableDiameter.setText("50");
            }
        } catch (NumberFormatException nfe) {
            tableDiameter.setText("1");
        }
    }//GEN-LAST:event_tableDiameterFocusLost

    private void addTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTableBtnActionPerformed
        if(_furnitureManager.checkOrderCapacity()){
            
            int idNumber = Integer.parseInt(tableIdNumber.getText());
            
            if(_furnitureManager.checkIdNumberExists(idNumber)){
                JOptionPane.showMessageDialog(jPanel4, "Oops, ID in use.");
                return;
            }
                
            String woodType = tableWoodtype.getSelectedItem().toString();
            int qty = Integer.parseInt(tableQty.getText());
            float diameter = Integer.parseInt(tableDiameter.getText());
            String base = woodenBase.isSelected() ? "Wooden Base" : "Chrome Base";
            
            Table newTable = _furnitureManager.addNewTable(idNumber, woodType, qty, diameter, base);
            this.addGridImage(newTable.image, _furnitureManager.getOrderGridPosition(newTable.idNumber), newTable.idNumber);
            this.updateTotalPriceGUI();
            closeTableFormActionPerformed(evt);
        }
        else{
            JOptionPane.showMessageDialog(jPanel4, "Oops, you've reached the maximum number of items that can be added into cart.");
        }
    }//GEN-LAST:event_addTableBtnActionPerformed

    private void addDeskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeskBtnActionPerformed
        if(_furnitureManager.checkOrderCapacity()){
            int idNumber = Integer.parseInt(deskIdNumber.getText());
            
            if(_furnitureManager.checkIdNumberExists(idNumber)){
                JOptionPane.showMessageDialog(jPanel4, "Oops, ID in use.");
                return;
            }
                
            String woodType = deskWoodType.getSelectedItem().toString();
            int qty = Integer.parseInt(deskQty.getText());
            float width = Integer.parseInt(deskWidth.getText());
            float depth = Integer.parseInt(deskDepth.getText());
            int noOfDrawers = Integer.parseInt(deskDrawers.getSelectedItem().toString());
            Desk newDesk = _furnitureManager.addNewDesk(idNumber, woodType, qty, width, depth, noOfDrawers);
            this.addGridImage(newDesk.image, _furnitureManager.getOrderGridPosition(newDesk.idNumber), newDesk.idNumber);
            this.updateTotalPriceGUI();
            closeDeskBtnActionPerformed(evt);
        }
        else{
            JOptionPane.showMessageDialog(jPanel4, "Oops, you've reached the maximum number of items that can be added into cart.");
        }
    }//GEN-LAST:event_addDeskBtnActionPerformed

    private void closeDeskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeDeskBtnActionPerformed
       deskDialog.dispose();
       deskIdNumber.setText("1");
       deskQty.setText("1");
       deskWidth.setText("50");
       deskDepth.setText("50");
    }//GEN-LAST:event_closeDeskBtnActionPerformed

    private void mainAddDeskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainAddDeskActionPerformed
        deskDialog.setVisible(true);
        deskDialog.setSize(325,300);
        deskDialog.setLocationRelativeTo(jPanel4);
    }//GEN-LAST:event_mainAddDeskActionPerformed

    private void deskIdNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deskIdNumberFocusLost
        try {
            int x = Integer.parseInt(deskIdNumber.getText());
        } catch (NumberFormatException nfe) {
            deskIdNumber.setText("1");
        }
    }//GEN-LAST:event_deskIdNumberFocusLost

    private void deskQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deskQtyFocusLost
        try {
            int x = Integer.parseInt(deskQty.getText());
        } catch (NumberFormatException nfe) {
            deskQty.setText("1");
        }
    }//GEN-LAST:event_deskQtyFocusLost

    private void deskWidthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deskWidthFocusLost
        try {
            int x = Integer.parseInt(deskWidth.getText());
        } catch (NumberFormatException nfe) {
            deskWidth.setText("50");
        }
    }//GEN-LAST:event_deskWidthFocusLost

    private void deskDepthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deskDepthFocusLost
        try {
            int x = Integer.parseInt(deskDepth.getText());
        } catch (NumberFormatException nfe) {
            deskDepth.setText("50");
        }
    }//GEN-LAST:event_deskDepthFocusLost

    private void mainClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainClearAllActionPerformed
        
        for(Map.Entry item: _furnitureManager.getAllOrderGridPos().entrySet()){
            this.addGridImage("", Integer.parseInt(item.getValue().toString()), 0);
        }
        _furnitureManager.clearAllOrder();
        this.updateTotalPriceGUI();
        
    }//GEN-LAST:event_mainClearAllActionPerformed

    private void placeOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderBtnActionPerformed
        _furnitureManager.getSummaryOnConsole();
        paymentDetailsDialog.setVisible(true);
        paymentDetailsDialog.setSize(400,215);
        paymentDetailsDialog.setLocationRelativeTo(jPanel4);
    }//GEN-LAST:event_placeOrderBtnActionPerformed

    private void grid1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid1MouseClicked
        //labelMouseClickedListener
        checkEmptyGrid( grid1);
        gridClick(evt, grid1);
    }//GEN-LAST:event_grid1MouseClicked

    private void grid2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid2MouseClicked
        checkEmptyGrid(grid2);
        gridClick(evt, grid2);
    }//GEN-LAST:event_grid2MouseClicked

    private void grid3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid3MouseClicked
        checkEmptyGrid(grid3);
        gridClick(evt, grid3);
    }//GEN-LAST:event_grid3MouseClicked

    private void grid4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid4MouseClicked
        checkEmptyGrid(grid4);
        gridClick(evt, grid4);
    }//GEN-LAST:event_grid4MouseClicked

    private void grid5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid5MouseClicked
        checkEmptyGrid(grid5);
        gridClick(evt, grid5);
    }//GEN-LAST:event_grid5MouseClicked

    private void grid6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid6MouseClicked
        checkEmptyGrid(grid6);
        gridClick(evt, grid6);
    }//GEN-LAST:event_grid6MouseClicked

    private void grid7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid7MouseClicked
        checkEmptyGrid(grid7);
        gridClick(evt, grid7);
    }//GEN-LAST:event_grid7MouseClicked

    private void grid8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid8MouseClicked
        checkEmptyGrid(grid8);
        gridClick(evt, grid8);
    }//GEN-LAST:event_grid8MouseClicked

    private void grid9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid9MouseClicked
        checkEmptyGrid(grid9);
        gridClick(evt, grid9);
    }//GEN-LAST:event_grid9MouseClicked

    private void dialogImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dialogImgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dialogImgMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        paymentDetailsDialog.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!_furnitureManager.placeOrder(paymentPAN.getText(), paymentExpDate.getText(), paymentCardHolder.getText(), Integer.parseInt(paymentCVV.getText()))){
            JOptionPane.showMessageDialog(jPanel4, "Oops, Something went wrong");
        }
        else JOptionPane.showMessageDialog( jPanel4, "Order printed to file.");
        paymentDetailsDialog.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addChairBtn;
    private javax.swing.JButton addDeskBtn;
    private javax.swing.JButton addTableBtn;
    private javax.swing.ButtonGroup baseGroup;
    private javax.swing.JCheckBox chairArmRests;
    private javax.swing.JDialog chairDialog;
    private javax.swing.JTextField chairIdNumber;
    private javax.swing.JTextField chairQty;
    private javax.swing.JComboBox<String> chairWoodType;
    private javax.swing.JRadioButton chromeBase;
    private javax.swing.JButton closeChairForm;
    private javax.swing.JButton closeDeskBtn;
    private javax.swing.JButton closeTableForm;
    private javax.swing.JTextField deskDepth;
    private javax.swing.JDialog deskDialog;
    private javax.swing.JComboBox<String> deskDrawers;
    private javax.swing.JTextField deskIdNumber;
    private javax.swing.JTextField deskQty;
    private javax.swing.JTextField deskWidth;
    private javax.swing.JComboBox<String> deskWoodType;
    private javax.swing.JLabel dialogImg;
    private javax.swing.JLabel displayIdNumber;
    private javax.swing.JLabel displayItem;
    private javax.swing.JDialog displayItemDialog;
    private javax.swing.JLabel displayPrice;
    private javax.swing.JLabel displayQty;
    private javax.swing.JLabel displayTotalPrice;
    private javax.swing.JLabel displayWoodType;
    private javax.swing.JLabel grid1;
    private javax.swing.JLabel grid2;
    private javax.swing.JLabel grid3;
    private javax.swing.JLabel grid4;
    private javax.swing.JLabel grid5;
    private javax.swing.JLabel grid6;
    private javax.swing.JLabel grid7;
    private javax.swing.JLabel grid8;
    private javax.swing.JLabel grid9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton mainAddChairBtn;
    private javax.swing.JButton mainAddDesk;
    private javax.swing.JButton mainAddTable;
    private javax.swing.JButton mainClearAll;
    private javax.swing.JLabel mainTotalotalPrice;
    private javax.swing.JTextField paymentCVV;
    private javax.swing.JTextField paymentCardHolder;
    private javax.swing.JDialog paymentDetailsDialog;
    private javax.swing.JTextField paymentExpDate;
    private javax.swing.JTextField paymentPAN;
    private javax.swing.JButton placeOrderBtn;
    private javax.swing.JDialog tableDialog;
    private javax.swing.JTextField tableDiameter;
    private javax.swing.JTextField tableIdNumber;
    private javax.swing.JTextField tableQty;
    private javax.swing.JComboBox<String> tableWoodtype;
    private javax.swing.JRadioButton woodenBase;
    // End of variables declaration//GEN-END:variables
}
